version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db


  db:
    container_name: pg_container
    image: postgres:14.5
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"